# -*- coding: utf-8 -*-
"""apriori.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1NCnudhEkDgUivT1Y2iyCLx_Sf3wo9Vlw

***Import required libraries.***
"""

import pandas as pd
import numpy as np
from google.colab import files

uploaded = files.upload()

"""***import dataset and print it.***"""

import io

dataset = pd.read_csv(io.StringIO(uploaded['Market_Basket_Optimisation.csv'].decode('utf-8')) , header = None)

print(dataset.head())

transactions = []
for i in range(0,7501):
  transactions.append([str(dataset.values[i,j]) for j in range(20)])

"""***Building the model and having results.***"""

from apyori import apriori

rules = apriori(transactions , min_support = 0.003 , min_confidence = 0.2, min_lift = 3 , min_length = 2)

results = list(rules)